### ISSUE TITLE
Missing definitions

### ISSUE THREAD

**Issue by ksuderman** [lapps/vocabulary-pages#6]
Definitions are required for the following annotation types:

 - [ ] NounChunk
 - [ ] VerbChunk

**Comment by ksuderman** [comment]
@nancyide Could you verify that http://vocab.lappsgrid.org reflects the changes you made?

**Comment by nancyide** [comment]
I am not entirely happy with the description of targets on span and inherited by everything under it. Could we say:

IDs of a sequence of annotations covering the span of text referred to by this annotation. Used as an alternative to “start” and “end” to point to component annotations (e.g., a token sequence) rather than directly into primary data, or to link two or more annotations (e.g., in a coreference annotation).


> On Oct 26, 2015, at 12:35 AM, Keith Suderman <notifications@github.com> wrote:
> 
> @nancyide <https://github.com/nancyide> Could you verify that http://vocab.lappsgrid.org <http://vocab.lappsgrid.org/> reflects the changes you made?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/lapps/vocabulary-pages/issues/6#issuecomment-150987615>.
> 

-----------------------------------------------------

Nancy Ide
Professor of Computer Science

Department of Computer Science
Vassar College
Poughkeepsie, New York 12604-0520 
USA

tel: (+1 845) 437 5988
fax: (+1 845) 437 7498
email: ide@cs.vassar.edu
http://www.cs.vassar.edu/~ide

-----------------------------------------------------

**Comment by marcverhagen** [comment]
Sounds good to me.

**Comment by ksuderman** [comment]
I will go ahead and make the changes and mark this issue as done.  We can open new issues if there are other problems.
