### ISSUE TITLE
Features vs. Properties

### ISSUE THREAD

**Issue by reckart** [lapps/vocabulary-pages#81]
The LAPPS WSEV generically defines **Properties**, e.g. `start`, `end, `targets`, etc.

The LIF format makes a distinction between `properties` and `features`. Properties are defined directly on the JSON annotation object, while `features` are actually an embedded map:

```
{ "@type": "Token", "id": "tok0", "start": 0, "end": 4, "features": { "pos": "NNP" } },
```

From the WSEV it is not possible to see what is supposed to be a feature and what is supposed to be a property.

**Comment by marcverhagen** [comment]
Correct, in WSEV you cannot see the difference and conceptually it is all properties and in LIF some properties are expressed on the top-level of an annotations whereas the rest is in the features dictionary which is a dictionary of all other properties. However, it is confusing and I will add something to the LIF specifications on this. 

The distinction is there because of historical accident I think and in retrospect we should probably only have had `@type` and `properties` as attributes on annotations. Changing this is tricky since it breaks backward compatibility.

**Comment by marcverhagen** [comment]
Some clarifications were added to the lapps.github.io pages (see https://github.com/lapps/lapps.github.io/commit/3d5e4661bd781e574c7a881f76e7768f55bbb6e6).
